# Generated by Django 3.1.1 on 2020-09-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='x', to='libraryapp.Genre'),
        ),
    ]
