# Generated by Django 3.1.1 on 2020-09-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20200910_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='libraryapp.Genre'),
        ),
    ]
